;; This modifies the ibuffer keymap
(eval-after-load 'ibuffer
  '(progn
    (evil-set-initial-state 'ibuffer-mode 'normal)
    (evil-define-key 'normal ibuffer-mode-map (kbd "j") 'evil-next-line)
    (evil-define-key 'normal ibuffer-mode-map (kbd "k") 'evil-previous-line)
    (evil-define-key 'normal ibuffer-mode-map (kbd "l") 'ibuffer-visit-buffer)
    (evil-define-key 'normal ibuffer-mode-map (kbd "e") 'ibuffer-visit-buffer)
    (evil-define-key 'normal ibuffer-mode-map (kbd "o") 'ibuffer-visit-buffer-other-window)
    (evil-define-key 'normal ibuffer-mode-map (kbd "C-o") 'ibuffer-visit-buffer-other-window-noselect)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M-o") 'ibuffer-visit-buffer-1-window)
    (evil-define-key 'normal ibuffer-mode-map (kbd "J") 'ibuffer-jump-to-buffer)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M-s a C-o") 'ibuffer-do-occur)

    (evil-define-key 'normal ibuffer-mode-map (kbd "=") 'ibuffer-diff-with-file)

    (evil-define-key 'normal ibuffer-mode-map (kbd "m") 'ibuffer-mark-forward)
    (evil-define-key 'normal ibuffer-mode-map (kbd "u") 'ibuffer-unmark-forward)
    (evil-define-key 'normal ibuffer-mode-map (kbd "DEL") 'ibuffer-unmark-backward)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M-DEL") 'ibuffer-unmark-all)
    (evil-define-key 'normal ibuffer-mode-map (kbd "t") 'ibuffer-toggle-marks)
    (evil-define-key 'normal ibuffer-mode-map (kbd "v") 'ibuffer-toggle-marks)

    (evil-define-key 'normal ibuffer-mode-map (kbd "* *") 'ibuffer-unmark-all)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* M") 'ibuffer-mark-by-mode)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* m") 'ibuffer-mark-modified-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* u") 'ibuffer-mark-unsaved-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* s") 'ibuffer-mark-special-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* r") 'ibuffer-mark-read-only-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* /") 'ibuffer-mark-dired-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* e") 'ibuffer-mark-dissociated-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* h") 'ibuffer-mark-help-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd "* z") 'ibuffer-mark-compressed-file-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd ".") 'ibuffer-mark-old-buffers)
    (evil-define-key 'normal ibuffer-mode-map (kbd "d") 'ibuffer-mark-for-delete)
    (evil-define-key 'normal ibuffer-mode-map (kbd "C-d") 'ibuffer-mark-for-delete-backwards)
    (evil-define-key 'normal ibuffer-mode-map (kbd "x") 'ibuffer-do-kill-on-deletion-marks)
    (evil-define-key 'normal ibuffer-mode-map (kbd "C-x v") 'ibuffer-do-view-horizontally)
    (evil-define-key 'normal ibuffer-mode-map (kbd "C-c C-a") 'ibuffer-auto-mode)
    (evil-define-key 'normal ibuffer-mode-map (kbd "C-x 4 RET") 'ibuffer-visit-buffer-other-window)
    (evil-define-key 'normal ibuffer-mode-map (kbd "C-x 5 RET") 'ibuffer-visit-buffer-other-frame)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M-}") 'ibuffer-forward-next-marked)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M-{") 'ibuffer-backwards-next-marked)
    (evil-define-key 'normal ibuffer-mode-map (kbd "g") 'ibuffer-update)
    (evil-define-key 'normal ibuffer-mode-map (kbd "`") 'ibuffer-switch-format)
    (evil-define-key 'normal ibuffer-mode-map (kbd "-") 'ibuffer-add-to-tmp-hide)
    (evil-define-key 'normal ibuffer-mode-map (kbd "+") 'ibuffer-add-to-tmp-show)
    (evil-define-key 'normal ibuffer-mode-map (kbd "b") 'ibuffer-bury-buffer)
    (evil-define-key 'normal ibuffer-mode-map (kbd ",") 'ibuffer-toggle-sorting-mode)
    (evil-define-key 'normal ibuffer-mode-map (kbd "s i") 'ibuffer-invert-sorting)
    (evil-define-key 'normal ibuffer-mode-map (kbd "s a") 'ibuffer-do-sort-by-alphabetic)
    (evil-define-key 'normal ibuffer-mode-map (kbd "s v") 'ibuffer-do-sort-by-recency)
    (evil-define-key 'normal ibuffer-mode-map (kbd "s s") 'ibuffer-do-sort-by-size)
    (evil-define-key 'normal ibuffer-mode-map (kbd "s f") 'ibuffer-do-sort-by-filename/process)
    (evil-define-key 'normal ibuffer-mode-map (kbd "s m") 'ibuffer-do-sort-by-major-mode)
    ;; (evil-define-key 'normal ibuffer-mode-map (kbd "/") 'evil-ex-search-forward)
    ;; (evil-define-key 'normal ibuffer-mode-map (kbd "?") 'evil-ex-search-backward)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f m") 'ibuffer-filter-by-used-mode)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f M") 'ibuffer-filter-by-derived-mode)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f n") 'ibuffer-filter-by-name)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f c") 'ibuffer-filter-by-content)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f e") 'ibuffer-filter-by-predicate)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f f") 'ibuffer-filter-by-filename)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f >") 'ibuffer-filter-by-size-gt)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f <") 'ibuffer-filter-by-size-lt)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f r") 'ibuffer-switch-to-saved-filters)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f a") 'ibuffer-add-saved-filters)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f x") 'ibuffer-delete-saved-filters)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f d") 'ibuffer-decompose-filter)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f s") 'ibuffer-save-filters)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f p") 'ibuffer-pop-filter)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f !") 'ibuffer-negate-filter)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f t") 'ibuffer-exchange-filters)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f TAB") 'ibuffer-exchange-filters)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f o") 'ibuffer-or-filter)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f g") 'ibuffer-filters-to-filter-group)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f P") 'ibuffer-pop-filter-group)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f D") 'ibuffer-decompose-filter-group)
    (evil-define-key 'normal ibuffer-mode-map (kbd "f f") 'ibuffer-filter-disable)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M-n") 'ibuffer-forward-filter-group)
    (evil-define-key 'normal ibuffer-mode-map (kbd "\t") 'ibuffer-forward-filter-group)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M-p") 'ibuffer-backward-filter-group)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M-j") 'ibuffer-jump-to-filter-group)
    (evil-define-key 'normal ibuffer-mode-map (kbd "C-k") 'ibuffer-kill-line)
    (evil-define-key 'normal ibuffer-mode-map (kbd "C-y") 'ibuffer-yank)
    (evil-define-key 'normal ibuffer-mode-map (kbd "/ S") 'ibuffer-save-filter-groups)
    (evil-define-key 'normal ibuffer-mode-map (kbd "/ R") 'ibuffer-switch-to-saved-filter-groups)
    (evil-define-key 'normal ibuffer-mode-map (kbd "/ X") 'ibuffer-delete-saved-filter-groups)
    (evil-define-key 'normal ibuffer-mode-map (kbd "/ \\") 'ibuffer-clear-filter-groups)

    (evil-define-key 'normal ibuffer-mode-map (kbd "% n") 'ibuffer-mark-by-name-regexp)
    (evil-define-key 'normal ibuffer-mode-map (kbd "% m") 'ibuffer-mark-by-mode-regexp)
    (evil-define-key 'normal ibuffer-mode-map (kbd "% f") 'ibuffer-mark-by-file-name-regexp)

    (evil-define-key 'normal ibuffer-mode-map (kbd "C-t") 'ibuffer-visit-tags-table)

    (evil-define-key 'normal ibuffer-mode-map (kbd "|") 'ibuffer-do-shell-command-pipe)
    (evil-define-key 'normal ibuffer-mode-map (kbd "!") 'ibuffer-do-shell-command-file)
    (evil-define-key 'normal ibuffer-mode-map (kbd "~") 'ibuffer-do-toggle-modified)
    (evil-define-key 'normal ibuffer-mode-map (kbd "A") 'ibuffer-do-view)
    (evil-define-key 'normal ibuffer-mode-map (kbd "D") 'ibuffer-do-delete)
    (evil-define-key 'normal ibuffer-mode-map (kbd "E") 'ibuffer-do-eval)
    (evil-define-key 'normal ibuffer-mode-map (kbd "F") 'ibuffer-do-shell-command-file)
    (evil-define-key 'normal ibuffer-mode-map (kbd "I") 'ibuffer-do-query-replace-regexp)
    (evil-define-key 'normal ibuffer-mode-map (kbd "H") 'ibuffer-do-view-other-frame)
    (evil-define-key 'normal ibuffer-mode-map (kbd "N") 'ibuffer-do-shell-command-pipe-replace)
    (evil-define-key 'normal ibuffer-mode-map (kbd "M") 'ibuffer-do-toggle-modified)
    (evil-define-key 'normal ibuffer-mode-map (kbd "O") 'ibuffer-do-occur)
    (evil-define-key 'normal ibuffer-mode-map (kbd "P") 'ibuffer-do-print)
    (evil-define-key 'normal ibuffer-mode-map (kbd "Q") 'ibuffer-do-query-replace)
    (evil-define-key 'normal ibuffer-mode-map (kbd "R") 'ibuffer-do-rename-uniquely)
    (evil-define-key 'normal ibuffer-mode-map (kbd "W") 'ibuffer-do-save)
    (evil-define-key 'normal ibuffer-mode-map (kbd "T") 'ibuffer-do-toggle-read-only)
    (evil-define-key 'normal ibuffer-mode-map (kbd "U") 'ibuffer-do-replace-regexp)
    (evil-define-key 'normal ibuffer-mode-map (kbd "V") 'ibuffer-do-revert)
    (evil-define-key 'normal ibuffer-mode-map (kbd "X") 'ibuffer-do-shell-command-pipe)
    (evil-define-key 'normal ibuffer-mode-map (kbd "w") 'ibuffer-copy-filename-as-kill)
  )
)

(provide 'my-ibuffer)

